name: Microsearch
favicon: null
layout_spectrum: 0.27138
typography_spectrum: 0.36529
title: Microsearch landing page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#695d96'
    - '#ffffff'
    - '#d6d2e3'
    - '#aca3c4'
    - '#8a80ad'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
