name: Microsearch
favicon: null
layout_spectrum: 0.9920677926857024
typography_spectrum: 0.9963240674696863
title: Microsearch landing page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7724165550898761
  lightness: 0.521533566294238
  saturation: 0.9387744162231684
  rhythmicContrast: 0.26622641272842884
purpose: []
